export const adjectives = [
  'active', 'agile', 'alert', 'ancient', 'angry', 'animated', 'anxious', 'arctic', 'arid', 'artistic',
  'ashy', 'autumn', 'awesome', 'bad', 'bald', 'basic', 'beautiful', 'beige', 'big', 'bitter',
  'black', 'bland', 'blind', 'blond', 'blue', 'blushing', 'bold', 'bouncy', 'brave', 'bright',
  'bronze', 'brown', 'bumpy', 'busy', 'buzzing', 'calm', 'careful', 'cheap', 'cheerful', 'chilly',
  'chubby', 'clean', 'clever', 'close', 'cloudy', 'cold', 'cool', 'copper', 'cozy', 'crazy',
  'crisp', 'cruel', 'crying', 'curly', 'cute', 'damp', 'daring', 'dark', 'darling', 'dear',
  'deep', 'dense', 'dirty', 'dizzy', 'double', 'drab', 'dry', 'dull', 'dusty', 'eager',
  'early', 'easy', 'elderly', 'elegant', 'empty', 'epic', 'exotic', 'faint', 'fair', 'fake',
  'fancy', 'far', 'fast', 'fat', 'fatal', 'few', 'fierce', 'fine', 'firm', 'flat',
  'fluffy', 'foamy', 'foggy', 'fond', 'free', 'fresh', 'friendly', 'frigid', 'frisky', 'frozen',
  'fuzzy', 'gentle', 'giant', 'glass', 'glowing', 'golden', 'good', 'grand', 'grassy', 'grave',
  'gray', 'great', 'greedy', 'green', 'grim', 'gross', 'hairy', 'half', 'happy', 'hard',
  'harsh', 'hazy', 'heavy', 'helpful', 'hidden', 'high', 'hollow', 'hot', 'huge', 'humble',
  'humid', 'hungry', 'icy', 'ill', 'infinite', 'instant', 'iron', 'itchy', 'jolly', 'juicy',
  'keen', 'kind', 'lame', 'large', 'late', 'lazy', 'leafy', 'lean', 'light', 'likable',
  'lively', 'lofty', 'lone', 'long', 'loose', 'loud', 'lovely', 'low', 'loyal', 'lucky',
  'lumpy', 'lush', 'mad', 'magic', 'magnificent', 'major', 'many', 'massive', 'meek', 'mellow',
  'merry', 'messy', 'mild', 'misty', 'modern', 'moist', 'muddy', 'mute', 'mysterious', 'naive',
  'narrow', 'nasty', 'natural', 'naughty', 'near', 'neat', 'needy', 'new', 'nice', 'nifty',
  'nimble', 'noisy', 'nutty', 'odd', 'old', 'orange', 'outer', 'pale', 'paltry', 'peaceful'
];

export const nouns = [
  'anchor', 'apple', 'apron', 'arrow', 'artist', 'ash', 'atlas', 'attic', 'avenue', 'baby',
  'badge', 'bag', 'balloon', 'bamboo', 'banana', 'banjo', 'bank', 'barrel', 'basin', 'basket',
  'bat', 'bath', 'beach', 'bead', 'beak', 'beam', 'bean', 'bear', 'beast', 'beaver',
  'bed', 'bee', 'bell', 'bench', 'berry', 'bird', 'bison', 'blade', 'blanket', 'blast',
  'blaze', 'block', 'board', 'boat', 'body', 'bone', 'book', 'boot', 'bottle', 'bowl',
  'box', 'boy', 'brain', 'branch', 'brass', 'bread', 'breeze', 'brick', 'bridge', 'brook',
  'broom', 'brush', 'bubble', 'bucket', 'bud', 'bug', 'bulb', 'bull', 'cabin', 'cable',
  'cactus', 'cage', 'cake', 'camel', 'camera', 'camp', 'canal', 'candle', 'candy', 'canyon',
  'cape', 'car', 'carpet', 'cart', 'castle', 'cat', 'cave', 'cell', 'chain', 'chair',
  'chalk', 'channel', 'chart', 'cheese', 'cheetah', 'cherry', 'chest', 'chief', 'child', 'chimney',
  'chip', 'circle', 'city', 'clam', 'clay', 'cliff', 'cloak', 'clock', 'cloud', 'clover',
  'club', 'coach', 'coal', 'coast', 'coat', 'cobra', 'coin', 'collar', 'colt', 'comb',
  'cone', 'cook', 'copper', 'coral', 'cord', 'cork', 'corner', 'cottage', 'cotton', 'couch',
  'cow', 'crab', 'crane', 'crater', 'creek', 'crest', 'cricket', 'crow', 'crown', 'crystal',
  'cube', 'cup', 'current', 'curtain', 'cushion', 'deer', 'den', 'desert', 'desk', 'dial',
  'diamond', 'disk', 'dock', 'dog', 'doll', 'dolphin', 'dome', 'donkey', 'door', 'dove',
  'dragon', 'drum', 'duck', 'dune', 'eagle', 'earth', 'echo', 'eel', 'egg', 'elbow',
  'elk', 'elm', 'engine', 'face', 'falcon', 'feather', 'fence', 'fern', 'ferry', 'field',
  'file', 'finch', 'finger', 'fir', 'fire', 'fish', 'flag', 'flame', 'flash', 'flask',
  'flute', 'fly', 'foam', 'fog', 'forest', 'fork', 'fox', 'frame', 'frog', 'frost'
];
